version: "3.7"
services:
  app:
    build:
      args:
        user: heshamelarj
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: hrm
    container_name: hrm-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - hrm

  db:
    image: mariadb
    container_name: hrm-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - hrm

  nginx:
    image: nginx:1.17-alpine
    container_name: travellist-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - hrm


  encore:
    image: node:10-alpine
    volumes:
      - .:/app
    ports:
      - "${DEV_SERVER_PORT:-8080}:8080"
    working_dir: /app
    command: [ "yarn", "dev-server", "--host=0.0.0.0" ]



networks:
  hrm:
    driver: bridge