version: "3.7"
services:
  app:
    build:
      args:
        user: heshamelarj
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: hrm
    container_name: hrm-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - hrm


  db:
    image: mariadb
    container_name: hrm-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - hrm

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=db

    depends_on:
      - db
    links:
      - db
    ports:
      - "8181:80"
    networks:
      - hrm






  nginx:
    image: nginx
    container_name: travellist-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - hrm


  npm:
    image: node:10-alpine
    volumes:
      - .:/app
    ports:
      - "${DEV_SERVER_PORT:-8080}:8080"
    working_dir: /app
    command: [ "yarn","dev-server" ]


volumes:
  mariadb-data:


networks:
  hrm:
    driver: bridge